//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataCliente
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comentarios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Comentarios()
        {
            this.Comentarios1 = new HashSet<Comentarios>();
        }
    
        public int ComentarioID { get; set; }
        public Nullable<int> PeliculaID { get; set; }
        public Nullable<int> UsuarioID { get; set; }
        public string Comentario { get; set; }
        public Nullable<System.DateTime> FechaComentario { get; set; }
        public Nullable<int> RespuestaAComentarioID { get; set; }
    
        public virtual Peliculas Peliculas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comentarios> Comentarios1 { get; set; }
        public virtual Comentarios Comentarios2 { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
