//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataCliente
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class tiusr30pl_PeliculasProgra11Entities : DbContext
    {
        public tiusr30pl_PeliculasProgra11Entities()
            : base("name=tiusr30pl_PeliculasProgra11Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ActoresStaff> ActoresStaff { get; set; }
        public virtual DbSet<CalificacionesExpertos> CalificacionesExpertos { get; set; }
        public virtual DbSet<Comentarios> Comentarios { get; set; }
        public virtual DbSet<Estado> Estado { get; set; }
        public virtual DbSet<ExpertosEnCalificaciones> ExpertosEnCalificaciones { get; set; }
        public virtual DbSet<Peliculas> Peliculas { get; set; }
        public virtual DbSet<Posters> Posters { get; set; }
        public virtual DbSet<Rol> Rol { get; set; }
        public virtual DbSet<RolesEnPelicula> RolesEnPelicula { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
    }
}
